### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by alejandro-andre** [giandifra/arcore_flutter_plugin#13]
I tried to compile and run the sample app, without any changes, and once you select any option on the menu list, nothing happens. 

My phone is a Samsung A70. 

At some point, a Java exception is thrown, I don't know if this is the cause:
java.lang.NoSuchFieldError: no "J" field "nativeHandle" in class "Lcom/google/ar/core/Session;" or its superclasses

The complete run log is:

D/ViewRootImpl@a3715af[MainActivity](23990): ViewPostIme pointer 0
D/ViewRootImpl@a3715af[MainActivity](23990): ViewPostIme pointer 1
V/DartMessenger(23990): Received message from Dart over channel 'flutter/accessibility'
V/DartMessenger(23990): Deferring to registered handler to process message.
V/AccessibilityChannel(23990): Received tap message.
V/DartMessenger(23990): Received message from Dart over channel 'flutter/platform'
V/DartMessenger(23990): Deferring to registered handler to process message.
V/PlatformChannel(23990): Received 'SystemSound.play' message.
V/DartMessenger(23990): Received message from Dart over channel 'flutter/platform'
V/DartMessenger(23990): Deferring to registered handler to process message.
V/PlatformChannel(23990): Received 'SystemChrome.setApplicationSwitcherDescription' message.
V/DartMessenger(23990): Received message from Dart over channel 'flutter/platform_views'
V/DartMessenger(23990): Deferring to registered handler to process message.
V/PlatformViewsChannel(23990): Received 'create' message.
D/Dialog  (23990): mIsSamsungBasicInteraction = false
D/Dialog  (23990): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
V/DartMessenger(23990): Setting handler for channel 'arcore_flutter_plugin_0'
D/SurfaceView(23990): setPackageUsesOwnResolution() (Java SurfaceView) for unknown app: 0x0 (false)
I/Filament(23990): FEngine (64 bits) created at 0x6f52600000 (threading is enabled)
D/Filament(23990): Using ASurfaceTexture
D/Filament(23990): FEngine resolved backend: OpenGL
I/SceneView(23990): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
I/DecorView(23990): mWindow.mActivityCurrentConfig is null.
I/DecorView(23990): createDecorCaptionView >> DecorView@94135c6[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/InputTransport(23990): Input channel constructed: fd=111
D/ViewRootImpl@3fab420[MainActivity](23990): setView = DecorView@94135c6[MainActivity] TM=true MM=false
I/flutter (23990): {dartType: ArCoreNode, shape: {radius: 0.1, dartType: ArCoreSphere, materials: [{color: [120, 66, 134, 244], texture: earth.jpg}]}, position: {x: 0.0, y: 0.0, z: -1.5}, name: bacjfqlelY^fow[_, children: []}
V/DartMessenger(23990): Received message from Dart over channel 'arcore_flutter_plugin_0'
V/DartMessenger(23990): Deferring to registered handler to process message.
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): arScenViewInit
W/Activity(23990): Can request only one set of permissions at a time
V/DartMessenger(23990): Received message from Dart over channel 'arcore_flutter_plugin_0'
V/DartMessenger(23990): Deferring to registered handler to process message.
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990):  addArCoreNode
I/flutter (23990): {dartType: ArCoreNode, shape: {height: 0.5, radius: 0.3, dartType: ArCoreCylinder, materials: [{color: [255, 244, 67, 54], reflectance: 1.0}]}, position: {x: 0.0, y: -0.5, z: -2.0}, name: otdbhfYwck_yqsdY, children: []}
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): name: bacjfqlelY^fow[_
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): shape: dartType: ArCoreSphere
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): radius: 0.1
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): material: color: 2017625844
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): argb: [120, 66, 134, 244]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): texture: earth.jpg
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): position: [x=0.0, y=0.0, z=-1.5]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): name: bacjfqlelY^fow[_
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): shape: dartType: ArCoreSphere
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): radius: 0.1
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): material: color: 2017625844
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): argb: [120, 66, 134, 244]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): texture: earth.jpg
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): position: [x=0.0, y=0.0, z=-1.5]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): parentNodeName: null
I/flutter (23990): {dartType: ArCoreNode, shape: {size: {x: 0.5, y: 0.5, z: 0.5}, dartType: ArCoreCube, materials: [{color: [120, 66, 134, 244], metallic: 1.0}]}, position: {x: -0.5, y: 0.5, z: -3.5}, name: swn_ducrZ\ps`jac, children: []}
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): onActivityPaused
V/LifecycleChannel(23990): Sending AppLifecycleState.inactive message.
V/DartMessenger(23990): Sending message with callback over channel 'flutter/lifecycle'
V/DartMessenger(23990): Received message from Dart over channel 'arcore_flutter_plugin_0'
V/DartMessenger(23990): Deferring to registered handler to process message.
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): name: otdbhfYwck_yqsdY
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): shape: dartType: ArCoreCylinder
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): radius: 0.3
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): height: 0.5
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): material: color: -769226
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): argb: [255, 244, 67, 54]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): reflectance: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): position: [x=0.0, y=-0.5, z=-2.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): name: otdbhfYwck_yqsdY
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): shape: dartType: ArCoreCylinder
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): radius: 0.3
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): height: 0.5
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): material: color: -769226
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): argb: [255, 244, 67, 54]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): reflectance: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): position: [x=0.0, y=-0.5, z=-2.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): parentNodeName: null
V/DartMessenger(23990): Received message from Dart over channel 'arcore_flutter_plugin_0'
V/DartMessenger(23990): Deferring to registered handler to process message.
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): name: swn_ducrZ\ps`jac
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): shape: dartType: ArCoreCube
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): radius: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): size: [x=0.5, y=0.5, z=0.5]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): material: color: 2017625844
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): argb: [120, 66, 134, 244]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): metallic: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): position: [x=-0.5, y=0.5, z=-3.5]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): name: swn_ducrZ\ps`jac
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): shape: dartType: ArCoreCube
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): radius: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): size: [x=0.5, y=0.5, z=0.5]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): material: color: 2017625844
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): argb: [120, 66, 134, 244]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): metallic: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): position: [x=-0.5, y=0.5, z=-3.5]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23990): parentNodeName: null
V/InputMethodManager(23990): Not IME target window, ignoring
D/SurfaceView(23990): onWindowVisibilityChanged(0) true com.google.ar.sceneform.ArSceneView{b1bfb33 V.E...... ......I. 0,0-0,0} of ViewRootImpl@3fab420[MainActivity]
D/ViewRootImpl@3fab420[MainActivity](23990): Relayout returned: old=[0,0][1080,2051] new=[0,0][1080,2051] result=0x7 surface={true 478673125376} changed=true
D/OpenGLRenderer(23990): eglCreateWindowSurface = 0x6f5788ed80, 0x6f73244010
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(23990): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): inserted otdbhfYwck_yqsdY
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(23990): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): inserted swn_ducrZ\ps`jac
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
D/ViewRootImpl@3fab420[MainActivity](23990): Relayout returned: old=[0,0][1080,2051] new=[0,0][1080,2051] result=0x3 surface={true 478673125376} changed=false
D/ViewRootImpl@3fab420[MainActivity](23990): MSG_RESIZED_REPORT: frame=[0,0][1080,2051] ci=[0,0][0,0] vi=[0,0][0,0] or=1
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(23990): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): inserted bacjfqlelY^fow[_
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
D/ViewRootImpl@a3715af[MainActivity](23990): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(23990): prepareNavigationBarInfo() DecorView@dc406b7[MainActivity]
D/InputMethodManager(23990): getNavigationBarColor() -855310
D/InputTransport(23990): Input channel destroyed: fd=88
D/ViewRootImpl@a3715af[MainActivity](23990): stopped(false) old=false
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): onActivityResumed
I/third_party/arcore/ar/core/android/sdk/session_create.cc(23990): Entering ArSession_create
I/third_party/arcore/ar/core/android/sdk/session_create.cc(23990): ARCore Version: APK version code: 190826056
I/third_party/arcore/ar/core/android/sdk/session_create.cc(23990): ARCore Version: SDK build name: 1.8
I/native  (23990): version_check.cc:23 ARCore Version: APK version:1.12.190826056
I/native  (23990): version_check.cc:24 ARCore Version: emulated SDK version:1.8.190310000
I/third_party/arcore/ar/core/android/sdk/session_create.cc(23990): Dynamite load ok.
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc(23990): Attempting to load native library arcore_c from package com.google.ar.core
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc(23990): Dynamite::LoadNativeRemoteLibrary handle=-4429280027413771307
I/native  (23990): session_create_implementation.cc:65 Entering createImplementationWithFeaturesAndSettings. ARCore SDK version: [1.8.190310000].
V/third_party/redwood/base/jni_common/jni_helper.cc(23990): JniHelper: attached thread (Called from line 300).
I/native  (23990): session_create_implementation_shared.cc:767 Persistent online recalibration is enabled by Phenotype.
I/native  (23990): online_calibration_manager.cc:53 OnlineCalibrationManager: Could not open /data/user/0/com.difrancescogianmarco.arcore_flutter_plugin_example/cache/arcore-online-recalibration for reading.
I/native  (23990): feature_provider.cc:82 Doing adaptive frequency feature extraction using KLT.
I/native  (23990): device_profile_conversions.cc:143 used_active_calibration: 2
I/native  (23990): device_profile_conversions.cc:143 used_active_calibration: 2
I/native  (23990): session_create_implementation_shared.cc:944 Datasource created with timeout = 4s, should_wait = false
I/native  (23990): android_camera.cc:141 Camera start operation timeout set to 4000 ms.
I/native  (23990): android_camera.cc:1644 Initializing camera manager.
D/VendorTagDescriptor(23990): addVendorDescriptor: vendor tag id 3854507339 added
I/native  (23990): android_camera.cc:1669 Camera manager initialized successfully with 2 cameras.
I/native  (23990): android_sensors.cc:82 Using uncalibrated accelerometer.
I/native  (23990): android_sensors.cc:120 Using uncalibrated magnetometer.
W/native  (23990): android_sensors.cc:132 Could not find pressure sensor.
I/native  (23990): android_platform_checks.cc:194 IsZeroRotationLandscape = false
I/native  (23990): device_profile_conversions.cc:143 used_active_calibration: 2
I/native  (23990): create_pursuit_tracker.cc:18 AugmentedRegion downsample mode from Phenotype: true
I/native  (23990): session_create_implementation_shared.cc:1170 CPU Image enable frame delay to compensate delay: true
I/native  (23990): legacy_calibration_provider_helpers.cc:96 Legacy IMU sigma values are used
I/native  (23990): config_helpers.cc:208 Failed to find IMU intrinsic covariance matrix in profile for id: 100
I/native  (23990): config_helpers.cc:61 Does not find camera intrinsic covariance matrix in profile for id 0
I/native  (23990): config_helpers.cc:134 Does not find extrinsic covariance matrix in profile for IMU id 100
I/native  (23990): vio_helper.cc:34 Use calibrated IMU scale factors.
I/native  (23990): vio_helper.cc:46 Use calibrated IMU misalignment factors.
I/native  (23990): feature_matcher_and_filter.cc:88 Enabled the robustification to large-sized and fast-moving objects on this mono-camera device.
I/native  (23990): android_camera.cc:141 Camera start operation timeout set to 4000 ms.
I/native  (23990): android_camera.cc:1644 Initializing camera manager.
I/native  (23990): android_camera.cc:1669 Camera manager initialized successfully with 2 cameras.
I/native  (23990): android_camera.cc:675 Camera 1: State CLOSED: Reset cleanly got to CLOSED state.
I/native  (23990): android_camera.cc:675 Camera 0: State CLOSED: Reset cleanly got to CLOSED state.
W/_plugin_exampl(23990): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/ARCore-ContextUtils(23990): The API key for use with the Google AR service could not be obtained!
D/NetworkSecurityConfig(23990): No Network Security Config specified, using platform default
I/tflite  (23990): Initialized TensorFlow Lite runtime.
I/native  (23990): planar_target_tracking_manager.h:109 Config of PlanarTargetTrackingManager:
I/native  (23990): -pose_refinement_with_detection_interval_ns: 0
I/native  (23990): -min_interval_between_detections_ns: 500000000
I/native  (23990): -filter_parallax: false
I/native  (23990): -filter_result: true
I/native  (23990): -multiple_targets: true
I/native  (23990): -mini_detection: true
I/native  (23990): -tracking_mode: 0
I/native  (23990): session_create_implementation.cc:251 createImplementationWithFeaturesAndSettings returning OK.
W/_plugin_exampl(23990): Accessing hidden method Landroid/media/Image;-><init>()V (light greylist, linking)
I/third_party/arcore/ar/core/android/sdk/arimage_jni.cc(23990): Loading AImage symbols
I/third_party/arcore/ar/core/android/sdk/image_metadata_jni.cc(23990): Loading ACameraMetadata symbols
I/native  (23990): device_provider.cc:1606 Identified device type: kA70q
W/System.err(23990): java.lang.NoSuchFieldError: no "J" field "nativeHandle" in class "Lcom/google/ar/core/Session;" or its superclasses
W/System.err(23990):    at com.google.ar.sceneform.ArSceneView.nativeReportEngineType(Native Method)
W/System.err(23990):    at com.google.ar.sceneform.ArSceneView.reportEngineType(SourceFile:159)
W/System.err(23990):    at com.google.ar.sceneform.ArSceneView.resumeSession(SourceFile:47)
W/System.err(23990):    at com.google.ar.sceneform.ArSceneView.resume(SourceFile:37)
W/System.err(23990):    at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView.onResume(ArCoreView.kt:200)
W/System.err(23990):    at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityResumed(ArCoreView.kt:102)
W/System.err(23990):    at android.app.Application.dispatchActivityResumed(Application.java:264)
W/System.err(23990):    at android.app.Activity.onResume(Activity.java:1403)
W/System.err(23990):    at io.flutter.app.FlutterActivity.onResume(FlutterActivity.java:100)
W/System.err(23990):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1416)
W/System.err(23990):    at android.app.Activity.performResume(Activity.java:7585)
W/System.err(23990):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4018)
W/System.err(23990):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4058)
W/System.err(23990):    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
W/System.err(23990):    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
W/System.err(23990):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
W/System.err(23990):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
W/System.err(23990):    at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(23990):    at android.os.Looper.loop(Looper.java:214)
W/System.err(23990):    at android.app.ActivityThread.main(ActivityThread.java:7094)
W/System.err(23990):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23990):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err(23990):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
E/third_party/arcore/ar/sceneform/android/jni/arsceneview_jni.cc(23990): nativeReportEngineType: Couldn't get session's nativeHandle
I/native  (23990): session.cc:925 Entering Session::Resume.
I/native  (23990): android_camera.cc:675 Camera 0: State CLOSED: Reset cleanly got to CLOSED state.
I/CameraManagerGlobal(23990): Connecting to camera service
D/VendorTagDescriptor(23990): addVendorDescriptor: vendor tag id 3854507339 added
I/native  (23990): android_sensors.cc:150 Starting thread.
I/native  (23990): cameras.cc:1118 Selected camera 0 stream 0 as feature extraction stream.
I/native  (23990): android_sensors.cc:28 Gyro min delay 4.808ms requesting 5ms
I/native  (23990): android_sensors.cc:28 Accel min delay 4.808ms requesting 5ms
I/native  (23990): session.cc:1055 Session::ResumeWithAnalytics returning OK.
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23990): Searching for surfaces
I/native  (23990): cameras.cc:1269 Camera changed state from CLOSED to OPEN: Camera 0: State CLOSED: Camera device opened successfully.
I/native  (23990): cameras.cc:1269 Camera changed state from OPEN to CAPTURING: Started capture session.
V/LifecycleChannel(23990): Sending AppLifecycleState.resumed message.
V/DartMessenger(23990): Sending message with callback over channel 'flutter/lifecycle'
D/ViewRootImpl@a3715af[MainActivity](23990): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(23990): prepareNavigationBarInfo() DecorView@dc406b7[MainActivity]
D/InputMethodManager(23990): getNavigationBarColor() -855310
D/InputMethodManager(23990): prepareNavigationBarInfo() DecorView@dc406b7[MainActivity]
D/InputMethodManager(23990): getNavigationBarColor() -855310
V/InputMethodManager(23990): Starting input: tba=com.difrancescogianmarco.arcore_flutter_plugin_example ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(23990): startInputInner - Id : 0
I/InputMethodManager(23990): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(23990): Input channel constructed: fd=124
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
I/native  (23990): timebase_helpers.cc:168 Timebase offset intialized to 0
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
W/native  (23990): gyro_helper.cc:44 Gyro samples do not cover << [ 0 ; 93983.3520211269933 ] sec. Use identity R. Gyro samples cover [ 93983.1930698000069 ; 93983.4843105809996 ] sec.
I/native  (23990): vio_initializer.cc:693 Not accepting frame as first BA keyframe.
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
I/native  (23990): vio_initializer.cc:693 Not accepting frame as first BA keyframe.
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
I/native  (23990): vio_initializer.cc:693 Not accepting frame as first BA keyframe.
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
I/native  (23990): ba_initialization_helpers.cc:371 Number of landmarks before eliminating short tracks 940, and after elimination 672
I/native  (23990): ba_initialization_helpers.cc:518 num_frames_for_dsolver: 4
I/native  (23990): ba_initialization_helpers.cc:519 number_of_landmarks_for_dsolver: 50
I/native  (23990): ba_initialization_helpers.cc:526 maximum_cam_meas_displacement_squared: 6.09747e-05
W/native  (23990): ba_initialization_helpers.cc:534 Maximum displacement of landmark measurements: 0.00780863
W/native  (23990): ba_initialization_helpers.cc:536 Motion is close to static motion, use pure propagation to initialize small scale BA
I/native  (23990): ba_initialization.cc:606 Deterministic initialization
I/native  (23990): ba_initialization_helpers.cc:675 Num. landmarks before pruning 672
I/native  (23990): ba_initialization_helpers.cc:676 Num. landmarks uninitialized: 0
I/native  (23990): ba_initialization_helpers.cc:688 Num. landmarks initialized after pruning 60
I/native  (23990): ba_initialization_helpers.cc:690 Num. landmarks uninitialized: 612
I/native  (23990): ba_initialization.cc:175 Intrinsic vector size of the camera 0 is 7
I/native  (23990): ba_initialization.cc:366 Initializer did not converge: Maximum number of iterations reached. Number of iterations: 18.
I/native  (23990): ba_initialization_helpers.h:168 Number of measurements used in BA initialization for temporal landmarks: 240
I/native  (23990): ba_initialization_helpers.h:170 Number of good measurements (i.e., reprojection errors <= 3 pixels) in BA initialization for temporal landmarks: 238
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
I/native  (23990): visual_inertial_filter.cc:773 VIO sliding window is initialized, with sliding window size 4
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
W/native  (23990): map_utils.cc:409 MapManager: Overwriting rolling shutter time from 0.0310976 to 0.0310976
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!
E/native  (23990): session.cc:1784 Invalid ray produced by view data!

**Comment by grau111** [comment]
in my flutter 1.9.1 project with android 3.5.1 i can't run the plugin! Just as I can't create sfb because sceneform has a bug. How to solve?
