### ISSUE TITLE
What happens when you launch it on a device lower than API 24?

### ISSUE THREAD

**Issue by JeromeGsq** [giandifra/arcore_flutter_plugin#16]
Hello,

Does this package support devices that are not ArCore compatible?
A message appears?

I tried this package on emulator 7.0 x86_64 and I have this error :
```
Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
D/EGL_emulation( 3312): eglMakeCurrent: 0x7fe47017fb20: ver 3 0 (tinfo 0x7fe4701653e0)
D/        ( 3312): HostConnection::get() New Host Connection established 0x7fe470182f60, tid 3326
D/        ( 3312): HostConnection::get() New Host Connection established 0x7fe470182de0, tid 3325
D/EGL_emulation( 3312): eglCreateContext: 0x7fe454598060: maj 3 min 0 rcv 3
D/EGL_emulation( 3312): eglMakeCurrent: 0x7fe454598060: ver 3 0 (tinfo 0x7fe45ec424c0)
E/eglCodecCommon( 3312): glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon( 3312): glUtilsParamSize: unknow param 0x00008824
I/Filament( 3312): FEngine (64 bits) created at 0x7fe44fe00000 (threading is enabled)
D/Filament( 3312): FEngine resolved backend: OpenGL
D/        ( 3312): HostConnection::get() New Host Connection established 0x7fe45b24e3c0, tid 3351
D/EGL_emulation( 3312): eglCreateContext: 0x7fe4576ae2c0: maj 3 min 0 rcv 3
D/EGL_emulation( 3312): eglMakeCurrent: 0x7fe4576ae2c0: ver 3 0 (tinfo 0x7fe472a39800)
E/eglCodecCommon( 3312): glUtilsParamSize: unknow param 0x00008cdf
E/eglCodecCommon( 3312): glUtilsParamSize: unknow param 0x00008824
E/eglCodecCommon( 3312): glUtilsParamSize: unknow param 0x00008a30
E/eglCodecCommon( 3312): glUtilsParamSize: unknow param 0x00008a34
I/SceneView( 3312): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView( 3312): arScenViewInit
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView( 3312): onActivityPaused
D/EGL_emulation( 3312): eglMakeCurrent: 0x7fe472a4a540: ver 3 0 (tinfo 0x7fe472bdd420)
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView( 3312): onActivityResumed
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView( 3312): onActivityPaused
D/EGL_emulation( 3312): eglMakeCurrent: 0x7fe472a4a540: ver 3 0 (tinfo 0x7fe472bdd420)
D/AndroidRuntime( 3312): Shutting down VM
E/AndroidRuntime( 3312): FATAL EXCEPTION: main
E/AndroidRuntime( 3312): Process: com.orange.ofood_poc_ar, PID: 3312
E/AndroidRuntime( 3312): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.orange.ofood_poc_ar/com.google.ar.core.InstallActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime( 3312): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
E/AndroidRuntime( 3312): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
E/AndroidRuntime( 3312): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/AndroidRuntime( 3312): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
E/AndroidRuntime( 3312): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3312): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 3312): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/AndroidRuntime( 3312): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3312): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/AndroidRuntime( 3312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
E/AndroidRuntime( 3312): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime( 3312): 	at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityCreated(ArCoreView.kt)
E/AndroidRuntime( 3312): 	at android.app.Application.dispatchActivityCreated(Application.java:197)
E/AndroidRuntime( 3312): 	at android.app.Activity.onCreate(Activity.java:961)
E/AndroidRuntime( 3312): 	at com.google.ar.core.InstallActivity.onCreate(InstallActivity.java:4)
E/AndroidRuntime( 3312): 	at android.app.Activity.performCreate(Activity.java:6662)
```

Flutter doctor : 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
• No issues found!
```

Thank you

**Comment by giandifra** [comment]
Hi, I use [Sceneform](https://developers.google.com/ar/develop/java/sceneform).
Sceneform requires minSdkVersion >= 24.
