### ISSUE TITLE
my app keeps stopping

### ISSUE THREAD

**Issue by yash365** [giandifra/arcore_flutter_plugin#2]
Used the example code mentioned in [https://pub.dartlang.org/packages/arcore_flutter_plugin#example](url)

Getting the following error message in the console while running the app:
`Launching lib/main.dart on Nokia 8 1 in debug mode...
Initializing gradle...                                              1.6s
Resolving dependencies...                                           2.8s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3.9s
Built build\app\outputs\apk\debug\app-debug.apk.
I/Filament(32511): FEngine (64 bits) created at 0x7441400000 (threading is enabled)
D/Filament(32511): Using ASurfaceTexture
D/Filament(32511): FEngine resolved backend: OpenGL
I/SceneView(32511): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
I/DecorView(32511): It non-support bigbang
I/PhoneWindow(32511): generateLayout isLightNavi false, Visibility: 0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): arScenViewInit
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): name: [yatd]nm_t[vjxuy
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): shape: dartType: ArCoreSphere
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): radius: 0.2
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): material: color: -10011977
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): argb: [255, 103, 58, 183]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): position: [x=0.0, y=0.0, z=-1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): name: [yatd]nm_t[vjxuy
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): shape: dartType: ArCoreSphere
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): radius: 0.2
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): material: color: -10011977
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): argb: [255, 103, 58, 183]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): position: [x=0.0, y=0.0, z=-1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): name: [gpdlnxua\_upkpw
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): shape: dartType: ArCoreCube
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): radius: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): size: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): material: color: -1499549
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): argb: [255, 233, 30, 99]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): metallic: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): position: [x=-0.5, y=-0.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): name: [gpdlnxua\_upkpw
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): shape: dartType: ArCoreCube
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): radius: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): size: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): material: color: -1499549
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): argb: [255, 233, 30, 99]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): metallic: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): position: [x=-0.5, y=-0.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): name: wwmufjcephkh\ttj
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): shape: dartType: ArCoreCylinder
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): radius: 0.3
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): height: 0.4
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): material: color: -11751600
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): argb: [255, 76, 175, 80]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): reflectance: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): position: [x=0.0, y=-2.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): name: wwmufjcephkh\ttj
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): shape: dartType: ArCoreCylinder
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): radius: 0.3
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): height: 0.4
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): material: color: -11751600
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): argb: [255, 76, 175, 80]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): texture: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): reflectance: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): position: [x=0.0, y=-2.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(32511): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): onActivityPaused
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(32511): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(32511): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(32511): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(32511): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
W/ActivityThread(32511): handleWindowVisibility: no activity for token android.os.BinderProxy@9dcadac
D/AndroidRuntime(32511): Shutting down VM
E/AndroidRuntime(32511): FATAL EXCEPTION: main
E/AndroidRuntime(32511): Process: com.example.flutter_ar, PID: 32511
E/AndroidRuntime(32511): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.flutter_ar/com.google.ar.core.InstallActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(32511):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
E/AndroidRuntime(32511):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3063)
E/AndroidRuntime(32511):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(32511):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(32511):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(32511):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1823)
E/AndroidRuntime(32511):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(32511):        at android.os.Looper.loop(Looper.java:198)
E/AndroidRuntime(32511):        at android.app.ActivityThread.main(ActivityThread.java:6729)
E/AndroidRuntime(32511):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32511):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(32511):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/AndroidRuntime(32511): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(32511):        at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityCreated(Unknown Source:7)
E/AndroidRuntime(32511):        at android.app.Application.dispatchActivityCreated(Application.java:220)
E/AndroidRuntime(32511):        at android.app.Activity.onCreate(Activity.java:1048)
E/AndroidRuntime(32511):        at com.google.ar.core.InstallActivity.onCreate(InstallActivity.java:4)
E/AndroidRuntime(32511):        at android.app.Activity.performCreate(Activity.java:7136)
E/AndroidRuntime(32511):        at android.app.Activity.performCreate(Activity.java:7127)
E/AndroidRuntime(32511):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
E/AndroidRuntime(32511):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
E/AndroidRuntime(32511):        ... 11 more
Syncing files to device Nokia 8 1...                             1,536ms`

**Comment by giandifra** [comment]
hi, did you try other native application with ARCore ? 
Do you have ARCore installed in you device? 
I will check installation process of ARCore  of my plugin...

**Comment by yash365** [comment]
I don't have arcore install in my device... how can I download it ?

**Comment by giandifra** [comment]
[here](https://play.google.com/store/apps/details?id=com.google.ar.core&hl=it)

**Comment by yash365** [comment]
it worked and now the app the running great

**Comment by obitodarky** [comment]
@giandifra 
I had the same issue but I was unable to install arcore. It says that my device isn't compatible. However, I have my device is arm-64 with Android 9 and API 28. What is the issue!?

**Comment by giandifra** [comment]
> @giandifra
> I had the same issue but I was unable to install arcore. It says that my device isn't compatible. However, my device is arm-64 with Android 9 and API 28. What is the issue!?

Check if you device is supported [here](https://developers.google.com/ar/discover/supported-devices)
