### ISSUE TITLE
The Application Crashes and stops, 

### ISSUE THREAD

**Issue by Chaitanyaha** [giandifra/arcore_flutter_plugin#27]
D/Dialog  (17859): mIsSamsungBasicInteraction = false
D/Dialog  (17859): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/ArCoreViewFactory(17859): 0
I/ArCoreViewFactory(17859): {type=standard}
D/SurfaceView(17859): setPackageUsesOwnResolution() (Java SurfaceView) for unknown app: 0x0 (false)
I/Filament(17859): FEngine (32 bits) created at 0xbf300000 (threading is enabled)
D/Filament(17859): Using ASurfaceTexture
D/Filament(17859): FEngine resolved backend: OpenGL
I/SceneView(17859): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
I/DecorView(17859): mWindow.mActivityCurrentConfig is null.
I/DecorView(17859): createDecorCaptionView >> DecorView@3e45afd[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/InputTransport(17859): Input channel constructed: fd=104
D/ViewRootImpl@e93979f[MainActivity](17859): setView = DecorView@3e45afd[MainActivity] TM=true MM=false
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(17859): arScenViewInit
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(17859): onActivityPaused
V/InputMethodManager(17859): Not IME target window, ignoring
D/SurfaceView(17859): onWindowVisibilityChanged(0) true com.google.ar.sceneform.ArSceneView{49bc48e V.E...... ......I. 0,0-0,0} of ViewRootImpl@e93979f[MainActivity]
D/ViewRootImpl@e93979f[MainActivity](17859): Relayout returned: old=[0,0][720,1320] new=[0,0][720,1320] result=0x7 surface={true 3304056832} changed=true
D/mali_winsys(17859): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000,  [720x1320]-format:1
D/OpenGLRenderer(17859): eglCreateWindowSurface = 0xdd6fc280, 0xc4efe808
D/SurfaceView(17859): setPackageUsesOwnResolution() (Java SurfaceView) for com.example.proj_ar: 720x1320 (false)
D/SurfaceView(17859): show() Surface(name=SurfaceView - Sys2037:com.example.proj_ar/com.example.proj_ar.MainActivity@49bc48e@0[17859])/@0x5e6fd6d com.google.ar.sceneform.ArSceneView{49bc48e V.E...... ......ID 0,0-720,1320}
D/SurfaceView(17859): surfaceCreated 1 #8 com.google.ar.sceneform.ArSceneView{49bc48e V.E...... ......ID 0,0-720,1320}
D/SurfaceView(17859): surfaceChanged (720,1320) 1 #8 com.google.ar.sceneform.ArSceneView{49bc48e V.E...... ......ID 0,0-720,1320}
D/ViewRootImpl@e93979f[MainActivity](17859): Relayout returned: old=[0,0][720,1320] new=[0,0][720,1320] result=0x3 surface={true 3304056832} changed=false
D/ViewRootImpl@e93979f[MainActivity](17859): MSG_RESIZED: frame=[0,0][720,1320] ci=[0,0][0,0] vi=[0,0][0,0] or=1
D/ViewRootImpl@6377c8c[MainActivity](17859): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(17859): prepareNavigationBarInfo() DecorView@ef38a1d[MainActivity]
D/InputMethodManager(17859): getNavigationBarColor() -855310
D/InputTransport(17859): Input channel destroyed: fd=94
D/ViewRootImpl@6377c8c[MainActivity](17859): stopped(false) old=false
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(17859): onActivityResumed
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(17859): onResume()
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(17859): session is null
I/com.difrancescogianmarco.arcore_flutter_plugin.utils.ArCoreUtils(17859): INSTALL REQUESTED
D/ViewRootImpl@6377c8c[MainActivity](17859): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(17859): prepareNavigationBarInfo() DecorView@ef38a1d[MainActivity]
D/InputMethodManager(17859): getNavigationBarColor() -855310
D/InputMethodManager(17859): prepareNavigationBarInfo() DecorView@ef38a1d[MainActivity]
D/InputMethodManager(17859): getNavigationBarColor() -855310
V/InputMethodManager(17859): Starting input: tba=com.example.proj_ar ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(17859): startInputInner - Id : 0
I/InputMethodManager(17859): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(17859): Input channel constructed: fd=111
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(17859): onActivityPaused
W/ActivityThread(17859): handleWindowVisibility: no activity for token android.os.BinderProxy@d3f00c6
D/ViewRootImpl@6377c8c[MainActivity](17859): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(17859): prepareNavigationBarInfo() DecorView@ef38a1d[MainActivity]
D/InputMethodManager(17859): getNavigationBarColor() -855310
D/AndroidRuntime(17859): Shutting down VM
E/AndroidRuntime(17859): FATAL EXCEPTION: main
E/AndroidRuntime(17859): Process: com.example.proj_ar, PID: 17859
E/AndroidRuntime(17859): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.proj_ar/com.google.ar.core.InstallActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(17859): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3126)
E/AndroidRuntime(17859): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3269)
E/AndroidRuntime(17859): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(17859): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(17859): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(17859): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1960)
E/AndroidRuntime(17859): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17859): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17859): 	at android.app.ActivityThread.main(ActivityThread.java:7081)
E/AndroidRuntime(17859): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17859): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(17859): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(17859): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(17859): 	at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityCreated(Unknown Source:7)
E/AndroidRuntime(17859): 	at android.app.Application.dispatchActivityCreated(Application.java:245)
E/AndroidRuntime(17859): 	at android.app.Activity.onCreate(Activity.java:1108)
E/AndroidRuntime(17859): 	at com.google.ar.core.InstallActivity.onCreate(InstallActivity.java:4)
E/AndroidRuntime(17859): 	at android.app.Activity.performCreate(Activity.java:7340)
E/AndroidRuntime(17859): 	at android.app.Activity.performCreate(Activity.java:7331)
E/AndroidRuntime(17859): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
E/AndroidRuntime(17859): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3106)
E/AndroidRuntime(17859): 	... 11 more
I/Process (17859): Sending signal. PID: 17859 SIG: 9
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51572/fGe5k*******=/

**Comment by giandifra** [comment]
Have you check if your device is supported? [Supported Devices](https://developers.google.com/ar/discover/supported-devices)

**Comment by giandifra** [comment]
See #2

**Comment by giandifra** [comment]
Now the plugin make app with optional ArCore and you can check compatibility #11
