### ISSUE TITLE
what this error is ??????????????????/

### ISSUE THREAD

**Issue by anmolseth06** [giandifra/arcore_flutter_plugin#43]
Launching lib\main.dart on SM G610F in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
D/FlutterActivity(23104): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(23104): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(23104): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(23104): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(23104): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e9da906
D/FlutterActivityAndFragmentDelegate(23104): Executing Dart entrypoint: main, and sending initial route: /
Debug service listening on ws://127.0.0.1:51991/R2Xj6XJGFmU=/ws
Syncing files to device SM G610F...
V/Surface (23104): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/ArCoreViewFactory(23104): 0
I/ArCoreViewFactory(23104): {type=standard}
D/SurfaceView(23104): setPackageUsesOwnResolution() (Java SurfaceView) for unknown app: 0x0 (false)
I/Filament(23104): Filament library loaded.
I/Filament(23104): FEngine (32 bits) created at 0xb9b80000 (threading is enabled)
D/Filament(23104): FEngine resolved backend: OpenGL
I/SceneView(23104): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
D/InputTransport(23104): Input channel constructed: fd=99
D/ViewRootImpl@3e62266[MainActivity](23104): setView = DecorView@85be9a7[MainActivity] TM=true MM=false
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): arScenViewInit
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): onActivityPaused
I/flutter (23104): {dartType: ArCoreNode, shape: {radius: 0.2, dartType: ArCoreSphere, materials: [{color: [255, 103, 58, 183]}]}, position: {x: 0.0, y: 0.0, z: -1.0}, name: qul[giyqZ`[jhqid, children: []}
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104):  addArCoreNode
I/flutter (23104): {dartType: ArCoreNode, shape: {size: {x: 1.0, y: 1.0, z: 1.0}, dartType: ArCoreCube, materials: [{color: [255, 233, 30, 99], metallic: 1.0}]}, position: {x: -0.5, y: -0.5, z: -3.0}, name: dmiulj\_olYtmdf^, children: []}
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): name: qul[giyqZ`[jhqid
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): shape: dartType: ArCoreSphere
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): radius: 0.2
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): material: color: -10011977
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): argb: [255, 103, 58, 183]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): textureBytesLength: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): position: [x=0.0, y=0.0, z=-1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): name: qul[giyqZ`[jhqid
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): shape: dartType: ArCoreSphere
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): radius: 0.2
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): material: color: -10011977
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): argb: [255, 103, 58, 183]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): textureBytesLength: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): position: [x=0.0, y=0.0, z=-1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): parentNodeName: null
I/flutter (23104): {dartType: ArCoreNode, shape: {height: 0.4, radius: 0.3, dartType: ArCoreCylinder, materials: [{color: [255, 76, 175, 80], reflectance: 1.0}]}, position: {x: 0.0, y: -2.5, z: -3.0}, name: alojttj]Zop`_ptb, children: []}
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): name: dmiulj\_olYtmdf^
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): shape: dartType: ArCoreCube
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): radius: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): size: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): material: color: -1499549
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): argb: [255, 233, 30, 99]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): textureBytesLength: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): metallic: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): position: [x=-0.5, y=-0.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): name: dmiulj\_olYtmdf^
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): shape: dartType: ArCoreCube
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): radius: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): size: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): height: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): material: color: -1499549
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): argb: [255, 233, 30, 99]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): textureBytesLength: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): metallic: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): reflectance: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): position: [x=-0.5, y=-0.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104):  addArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): name: alojttj]Zop`_ptb
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): shape: dartType: ArCoreCylinder
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): radius: 0.3
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): height: 0.4
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): material: color: -11751600
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): argb: [255, 76, 175, 80]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): textureBytesLength: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): reflectance: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): position: [x=0.0, y=-2.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): parentNodeName: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): dartType: ArCoreNode
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): name: alojttj]Zop`_ptb
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): shape: dartType: ArCoreCylinder
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): radius: 0.3
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): size: [x=0.0, y=0.0, z=0.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): height: 0.4
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): material: color: -11751600
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): argb: [255, 76, 175, 80]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): textureBytesLength: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): metallic: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): roughness: null
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): reflectance: 1.0
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): obcject3DFileName: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): objectUrl: null 
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): position: [x=0.0, y=-2.5, z=-3.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): scale: [x=1.0, y=1.0, z=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): rotation: [x=0.0, y=0.0, z=0.0, w=1.0]
I/com.difrancescogianmarco.arcore_flutter_plugin.NodeFactory(23104): parentNodeName: null
V/InputMethodManager(23104): Not IME target window, ignoring
D/SurfaceView(23104): onWindowVisibilityChanged(0) true ba85fb6 of ViewRootImpl@3e62266[MainActivity]
D/ViewRootImpl@3e62266[MainActivity](23104): dispatchAttachedToWindow
V/Surface (23104): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@3e62266[MainActivity](23104): Relayout returned: old=[0,0][0,0] new=[0,0][1080,1710] result=0x7 surface={valid=true 3143452672} changed=true
D/mali_winsys(23104): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1710]-format:1
D/OpenGLRenderer(23104): eglCreateWindowSurface = 0xb812b2d0, 0xbb5d4808
D/SurfaceView(23104): setPackageUsesOwnResolution() (Java SurfaceView) for com.aeologic.arkit: 1080x1710 (false)
D/SurfaceView(23104): BG show() Surface(name=Background for - SurfaceView - Sys2037:com.aeologic.arkit/com.aeologic.arkit.MainActivity@ba85fb6@0) com.google.ar.sceneform.ArSceneView{ba85fb6 V.E...... ......ID 0,0-1080,1710}
V/Surface (23104): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/SurfaceView(23104): surfaceCreated 1 #8 com.google.ar.sceneform.ArSceneView{ba85fb6 V.E...... ......ID 0,0-1080,1710}
D/SurfaceView(23104): surfaceChanged (1080,1710) 1 #8 com.google.ar.sceneform.ArSceneView{ba85fb6 V.E...... ......ID 0,0-1080,1710}
D/ViewRootImpl@9be5d48[MainActivity](23104): MSG_WINDOW_FOCUS_CHANGED 0
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(23104): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): inserted alojttj]Zop`_ptb
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(23104): material not null
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): inserted dmiulj\_olYtmdf^
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
I/com.difrancescogianmarco.arcore_flutter_plugin.RenderableCustomFactory(23104): material not null
I/zygote  (23104): Do partial code cache collection, code=29KB, data=29KB
I/zygote  (23104): After code cache collection, code=29KB, data=29KB
I/zygote  (23104): Increasing code cache capacity to 128KB
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): inserted qul[giyqZ`[jhqid
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): addNodeToSceneWithGeometry: NOT PARENT_NODE_NAME
D/ViewRootImpl@3e62266[MainActivity](23104): Relayout returned: old=[0,0][1080,1710] new=[0,0][1080,1710] result=0x3 surface={valid=true 3143452672} changed=false
D/ViewRootImpl@3e62266[MainActivity](23104): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1710) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl@9be5d48[MainActivity](23104): MSG_WINDOW_FOCUS_CHANGED 1
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): onActivityResumed
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): onResume()
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): session is null
I/com.difrancescogianmarco.arcore_flutter_plugin.utils.ArCoreUtils(23104): INSTALL REQUESTED
D/ViewRootImpl@9be5d48[MainActivity](23104): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 3245836288} changed=false
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(23104): onActivityPaused
D/ViewRootImpl@9be5d48[MainActivity](23104): MSG_WINDOW_FOCUS_CHANGED 0
D/AndroidRuntime(23104): Shutting down VM
E/AndroidRuntime(23104): FATAL EXCEPTION: main
E/AndroidRuntime(23104): Process: com.aeologic.arkit, PID: 23104
E/AndroidRuntime(23104): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.aeologic.arkit/com.google.ar.core.InstallActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(23104): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2974)
E/AndroidRuntime(23104): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
E/AndroidRuntime(23104): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(23104): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
E/AndroidRuntime(23104): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23104): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(23104): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/AndroidRuntime(23104): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23104): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/AndroidRuntime(23104): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
E/AndroidRuntime(23104): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(23104): 	at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityCreated(Unknown Source:7)
E/AndroidRuntime(23104): 	at android.app.Application.dispatchActivityCreated(Application.java:221)
E/AndroidRuntime(23104): 	at android.app.Activity.onCreate(Activity.java:1071)
E/AndroidRuntime(23104): 	at com.google.ar.core.InstallActivity.onCreate(InstallActivity.java:4)
E/AndroidRuntime(23104): 	at android.app.Activity.performCreate(Activity.java:7258)
E/AndroidRuntime(23104): 	at android.app.Activity.performCreate(Activity.java:7249)
E/AndroidRuntime(23104): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
E/AndroidRuntime(23104): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
E/AndroidRuntime(23104): 	... 9 more
Lost connection to device.
D/FlutterActivity(23180): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(23180): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(23180): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(23180): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(23180): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@e9da906
D/FlutterActivityAndFragmentDelegate(23180): Executing Dart entrypoint: main, and sending initial route: /
I/flutter (23180): {dartType: ArCoreNode, shape: {radius: 0.2, dartType: ArCoreSphere, materials: [{color: [255, 103, 58, 183]}]}, position: {x: 0.0, y: 0.0, z: -1.0}, name: g^YYnbakv[y]hvbc, children: []}
I/flutter (23180): {dartType: ArCoreNode, shape: {size: {x: 1.0, y: 1.0, z: 1.0}, dartType: ArCoreCube, materials: [{color: [255, 233, 30, 99], metallic: 1.0}]}, position: {x: -0.5, y: -0.5, z: -3.0}, name: ltbYoteg[xvZ\`vt, children: []}
I/flutter (23180): {dartType: ArCoreNode, shape: {height: 0.4, radius: 0.3, dartType: ArCoreCylinder, materials: [{color: [255, 76, 175, 80], reflectance: 1.0}]}, position: {x: 0.0, y: -2.5, z: -3.0}, name: p`xasm^h_un`vglf, children: []}
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:51991/R2Xj6XJGFmU=/

**Comment by alexxlagutin** [comment]
+1. Have the same issue. Any suggestions?

**Comment by pagach** [comment]
Does you device support arcore? Had the same problem but it worked on a newer device.

**Comment by BrutalCoding** [comment]
I've submitted a PR that might fix this issue, try again with that.
See my previous comment.
https://github.com/giandifra/arcore_flutter_plugin/issues/40#issuecomment-690846985
